// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordsBot.Common.Test;

namespace WordsBot.Common.Test.Migrations
{
    [DbContext(typeof(MockDbContext))]
    [Migration("20210708190628_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("WordsBot.Common.Models.GameSession", b =>
                {
                    b.Property<int>("GameSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentWord")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentWordNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("From")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("To")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalWordsCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameSessionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("WordsBot.Common.Models.TrainingTranslation", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Word")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "Word");

                    b.ToTable("TrainingTranslations");
                });

            modelBuilder.Entity("WordsBot.Common.Models.Translation", b =>
                {
                    b.Property<int>("TranslationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("From")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .HasColumnType("TEXT");

                    b.Property<string>("Values")
                        .HasColumnType("TEXT");

                    b.Property<string>("Word")
                        .HasColumnType("TEXT");

                    b.HasKey("TranslationId");

                    b.HasIndex("Word", "From", "To")
                        .IsUnique();

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("WordsBot.Common.Models.UserInfo", b =>
                {
                    b.Property<long>("UserInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("UserInfoId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
